#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.1.60.136, Tue Nov 28 15:54:20 2023

#define DB_VERSION_UNIQ_ID "0x73dc614e"

#endif //_DB_VERSION_H
